<?php

/**
 * @file
 * Contains zebra_system.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function zebra_system_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the zebra_system module.
    case 'help.page.zebra_system':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Progressive Decoupled initiative Zebra System Module, gives the user ability to enable and disable zebra background on the site.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
// function zebra_system_theme($existing, $type, $theme, $path) {
//   $templ_path = $path . '/templates/';

//   return [
//     'zebra_system' => [
//       'render element' => 'children',
//     ],
//   ];
// }

function zebra_system_preprocess_one_column(&$variables) {
  // Erase prefix and sufix for content
  if (isset($variables['content']['#prefix']) && isset($variables['content']['#suffix'])) {

    // Get form config.
    $config = \Drupal::service('config.factory')->getEditable('zebra_system.adminsettings');
    // Set enable_zebra_system if checked.
    $enable_zebra_system = intval($config->get('enable_zebra_system'));

    $variables['content']['#prefix'] = NULL;
    $variables['content']['#suffix'] = NULL;

    if (isset($variables['content']['main']['#prefix']) && isset($variables['content']['main']['#suffix'])) {
      $variables['content']['main']['#prefix'] = NULL;
      $variables['content']['main']['#suffix'] = NULL;

      // Create Zebra Wrapper if admin checkbox is set to Show zebra Systems.
      if($enable_zebra_system) {
        $variables['content']['main']['#prefix'] = '<div class="zebra-system-wrapper">';
        $variables['content']['main']['#suffix'] = '</div>';
      }
    }
  }
}

function zebra_system_preprocess_two_column(&$variables) {
  // Erase prefix and sufix for content
  if (isset($variables['content']['#prefix']) && isset($variables['content']['#suffix'])) {

    // Get form config.
    $config = \Drupal::service('config.factory')->getEditable('zebra_system.adminsettings');
    // Set enable_zebra_system if checked.
    $enable_zebra_system = intval($config->get('enable_zebra_system'));

    $variables['content']['#prefix'] = NULL;
    $variables['content']['#suffix'] = NULL;

    $templ_regions = $variables['content']['#layout']->get('regions');
    if (isset($templ_regions)
        && !empty($templ_regions)) {
      // For each region set prefix div zebra-wrapper
      foreach($templ_regions as $region => $value) {
        if (isset($variables['content'][$region]['#prefix']) && isset($variables['content'][$region]['#suffix'])) {
          $variables['content'][$region]['#prefix'] = NULL;
          $variables['content'][$region]['#suffix'] = NULL;

          // Create Zebra Wrapper if admin checkbox is set to Show zebra Systems.
          if($enable_zebra_system) {
            $variables['content'][$region]['#prefix'] = '<div class="zebra-system-wrapper">';
            $variables['content'][$region]['#suffix'] = '</div>';
          }
        }
      }
    }

  }
}

function zebra_system_preprocess_three_column(&$variables) {
  // Erase prefix and sufix for content
  if (isset($variables['content']['#prefix']) && isset($variables['content']['#suffix'])) {

    // Get form config.
    $config = \Drupal::service('config.factory')->getEditable('zebra_system.adminsettings');
    // Set enable_zebra_system if checked.
    $enable_zebra_system = intval($config->get('enable_zebra_system'));

    $variables['content']['#prefix'] = NULL;
    $variables['content']['#suffix'] = NULL;

    if (isset($variables['content']['top']['#prefix']) && isset($variables['content']['top']['#suffix'])) {
      $variables['content']['top']['#prefix'] = NULL;
      $variables['content']['top']['#suffix'] = NULL;

      // Create Zebra Wrapper if admin checkbox is set to Show zebra Systems.
      if($enable_zebra_system) {
        $variables['content']['top']['#prefix'] = '<div class="zebra-system-wrapper">';
        $variables['content']['top']['#suffix'] = '</div>';
      }
    }
  }
}

/**
 * Implements page_attachments().
 */
function zebra_system_page_attachments(array &$attachments) {
  $attachments['#attached']['library'][] = 'zebra_system/default';
  $attachments['#attached']['library'][] = 'zebra_system/styling';
}
